<a href="https://colab.research.google.com/github/shrikantkhule100-ux/PORTFOLIO/blob/main/Lesson_008_Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
data_array = np.array([1,2,3,4,5,6,7,8,5,6,4,3])

professional_2d = data_array.reshape(3,4)

print("orignal_list",numbres_array)
print("matrix:professional_2d")
print(professional_2d)

orignal_list [1 2 3 4 5 6 7 8 5 6 4 3]
matrix:professional_2d
[[1 2 3 4]
 [5 6 7 8]
 [5 6 4 3]]
