<a href="https://colab.research.google.com/github/shrikantkhule100-ux/PORTFOLIO/blob/main/lesson_006_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
matrix = np.array([[10,20,30],
                  [40,50,60],
                  [70,80,90]])
middle_value = matrix[1,1]

first_row = matrix[0,:]
last_column = matrix[:,2]
print("full matrix:\n",matrix)
print(" The middle value",middle_value)
print("The first row",first_row)
print("The last column",last_column)



full matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
 The middle value 50
The first row [10 20 30]
The last column [30 60 90]
